spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/detail_db
      username: root
      password: 10086
      driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB
  data:
    redis:
      port: 6379
      host: 1.0.0.86
      database: 0
      timeout: 10000

mybatis:
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.fzuswimassociation.pojo
  mapper-locations: classpath:/mappers/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



jwt:
  token:
    tokenExpiration: 24
    tokenSignKey: 10086
    server:
  port: 8080

flow-control:
  max-request: 2
  time-window: 10
  whether-enabled-or-not: false
